version: '3.8'

services:

  php-apache:
    container_name: docker_php_apache
    build: ./php-apache
    #    image: php:8.0.0-apache
    restart: always
    ports:
      - 1234:80
      - 443:443
    volumes:
      - ./laravel_project:/var/www/html

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker_mysql
    restart: always
    ports:
      - '3333:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: demo

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql_db

