version: '3.8'

services:

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker_mysql
    restart: always
    ports:
      - '3333:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: demo

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    container_name: docker_phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql_db

  redis_db:
    container_name: 'docker_redis'
    image: library/redis:6.0.9
    restart: always
    ports:
      - '6666:6379'

  phpredisadmin:
    container_name: docker_phpredisadmin
    image: erikdubbelboer/phpredisadmin
    restart: always
    depends_on:
      - redis_db
    ports:
      - '8889:80'
    environment:
      REDIS_1_HOST: redis_db
